- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items:
    - "{{play_hosts}}"
