- name: Bootstrap Ansible
  hosts: cm-*
  gather_facts: false
  tasks:
  - include: ../tasks/bootstrap-ansible.yaml

- hosts: cm-*
  vars_files:
    - ../vars/mms-keys.yaml
  tasks:
   - include: ../tasks/setup-hosts.yaml
   - include: ../tasks/setup-ssl.yaml
   - include: ../tasks/install-automation.yaml
